Rebuild node-syslog for node 0.8.2
Change-Id: I2237c1cd43da758df8480e4ef4d105b1030a158d

diff --git a/node-syslog/build/Makefile b/node-syslog/build/Makefile
--- a/node-syslog/build/Makefile
+++ b/node-syslog/build/Makefile
@@ -40,14 +40,6 @@ all_deps :=
 
 
 
-CC.target ?= $(CC)
-CFLAGS.target ?= $(CFLAGS)
-CXX.target ?= $(CXX)
-CXXFLAGS.target ?= $(CXXFLAGS) $(CPPFLAGS)
-LINK.target ?= $(LINK)
-LDFLAGS.target ?= $(LDFLAGS)
-AR.target ?= $(AR)
-
 # C++ apps need to be linked with g++.
 #
 # Note: flock is used to seralize linking. Linking is a memory-intensive
@@ -57,17 +49,29 @@ AR.target ?= $(AR)
 #   export LINK=g++
 #
 # This will allow make to invoke N linker processes as specified in -jN.
-LINK ?= flock $(builddir)/linker.lock $(CXX.target)
+LINK ?= flock $(builddir)/linker.lock $(CXX)
 
+CC.target ?= $(CC)
+CFLAGS.target ?= $(CFLAGS)
+CXX.target ?= $(CXX)
+CXXFLAGS.target ?= $(CXXFLAGS)
+LINK.target ?= $(LINK)
+LDFLAGS.target ?= $(LDFLAGS)
+AR.target ?= $(AR)
+ARFLAGS.target ?= crsT
+
+# N.B.: the logic of which commands to run should match the computation done
+# in gyp's make.py where ARFLAGS.host etc. is computed.
 # TODO(evan): move all cross-compilation logic to gyp-time so we don't need
 # to replicate this environment fallback in make as well.
 CC.host ?= gcc
 CFLAGS.host ?=
 CXX.host ?= g++
 CXXFLAGS.host ?=
-LINK.host ?= $(CXX.host)
+LINK.host ?= g++
 LDFLAGS.host ?=
 AR.host ?= ar
+ARFLAGS.host := crsT
 
 # Define a dir function that can handle spaces.
 # http://www.gnu.org/software/make/manual/make.html#Syntax-of-Functions
@@ -142,10 +146,7 @@ quiet_cmd_copy = COPY $@
 cmd_copy = ln -f "$<" "$@" 2>/dev/null || (rm -rf "$@" && cp -af "$<" "$@")
 
 quiet_cmd_alink = AR($(TOOLSET)) $@
-cmd_alink = rm -f $@ && $(AR.$(TOOLSET)) crs $@ $(filter %.o,$^)
-
-quiet_cmd_alink_thin = AR($(TOOLSET)) $@
-cmd_alink_thin = rm -f $@ && $(AR.$(TOOLSET)) crsT $@ $(filter %.o,$^)
+cmd_alink = rm -f $@ && $(AR.$(TOOLSET)) $(ARFLAGS.$(TOOLSET)) $@ $(filter %.o,$^)
 
 # Due to circular dependencies between libraries :(, we wrap the
 # special "figure out circular dependencies" flags around the entire
@@ -212,14 +213,15 @@ command_changed = $(or $(subst $(cmd_$(1)),,$(cmd_$(call replace_spaces,$@))),\
 #   $| -- order-only dependencies
 prereq_changed = $(filter-out FORCE_DO_CMD,$(filter-out $|,$?))
 
-# Helper that executes all postbuilds until one fails.
+# Helper that executes all postbuilds, and deletes the output file when done
+# if any of the postbuilds failed.
 define do_postbuilds
   @E=0;\
   for p in $(POSTBUILDS); do\
     eval $$p;\
-    E=$$?;\
-    if [ $$E -ne 0 ]; then\
-      break;\
+    F=$$?;\
+    if [ $$F -ne 0 ]; then\
+      E=$$F;\
     fi;\
   done;\
   if [ $$E -ne 0 ]; then\
@@ -316,8 +318,8 @@ ifeq ($(strip $(foreach prefix,$(NO_LOAD),\
 endif
 
 quiet_cmd_regen_makefile = ACTION Regenerating $@
-cmd_regen_makefile = cd $(srcdir); /usr/share/node-gyp/gyp/gyp -fmake --ignore-environment "--toplevel-dir=." -I/home/elliott/src/js/dash/node_modules/node-syslog/build/config.gypi -I/usr/share/node-gyp/addon.gypi -I/usr/include/nodejs/common.gypi "--depth=." "-Goutput_dir=." "--generator-output=build" "-Dlibrary=shared_library" "-Dvisibility=default" "-Dnode_root_dir=/usr/include/nodejs" "-Dmodule_root_dir=/home/elliott/src/js/dash/node_modules/node-syslog" binding.gyp
-Makefile: $(srcdir)/../../../../../../../usr/share/node-gyp/addon.gypi $(srcdir)/../../../../../../../usr/include/nodejs/common.gypi $(srcdir)/build/config.gypi $(srcdir)/binding.gyp
+cmd_regen_makefile = /home/elliott/.node-gyp/0.8.2/tools/gyp_addon -fmake --ignore-environment "--toplevel-dir=." -I/home/elliott/src/js/dash/node_modules/node-syslog/build/config.gypi -I/home/elliott/.node-gyp/0.8.2/tools/addon.gypi -I/home/elliott/.node-gyp/0.8.2/common.gypi "--depth=." "-Goutput_dir=." "--generator-output=build" "-Dlibrary=shared_library" "-Dvisibility=default" "-Dnode_root_dir=/home/elliott/.node-gyp/0.8.2" "-Dmodule_root_dir=/home/elliott/src/js/dash/node_modules/node-syslog" binding.gyp
+Makefile: $(srcdir)/../../../../../.node-gyp/0.8.2/tools/addon.gypi $(srcdir)/build/config.gypi $(srcdir)/binding.gyp $(srcdir)/../../../../../.node-gyp/0.8.2/common.gypi
 	$(call do_cmd,regen_makefile)
 
 # "all" is a concatenation of the "all" targets from all the included
